; PlatformIO configuration for ESP32 Treadmill BLE Bridge
; Board: ESP32-C3 SuperMini
;
; Architecture:
;   Treadmill Dionysis RUN500  <--BLE/FTMS-->  ESP32  <--BLE sensor profile-->  Speed and Cadense sensor profile

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.2
